sudo: required
services:
  - docker

before_install:
  - docker build -t maverickdev69/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maverickdev69/react-test npm test

after_success:
  - docker build -t maverickdev69/multi-client ./client
  - docker build -t maverickdev69/multi-nginx ./nginx
  - docker build -t maverickdev69/multi-server ./server
  - docker build -t maverickdev69/multi-worker ./worker
  #Login to  docker CLI
  - docker login -u "DOCKER_ID" -p "DOCKER_PASSWORD"
  # Take these images and push it to dockerhub
  - docker push maverickdev69/multi-client
  - docker push maverickdev69/multi-nginx
  - docker push maverickdev69/multi-server
  - docker push maverickdev69/multi-worker